spring.application.name=api-rest-persona-jenkins



#PROPERTIES DATASOURCE
#JAVA 8,7,11 ORACLE.JDBC.DRIVER.ORACLEDRIVER
#JAVA 17,21,24,25 ORACLE.JDBC.ORACLEDRIVER
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=System
spring.datasource.password=admin123

#PROPERTIES HIBERNATE & JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

#Properties Spring_batch
spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=always

#SERVER APACHE TOMCAT,DEFAULT PORT 8080
#server.port=7272
server.port=7575